version: '2'
services:
  geoserver:
    image: "kartoza/geoserver:latest"
    ports:
     - "58080:8080"
  postgis:
    image: "starefossen/pgrouting:latest"
  pgAdmin:
    image: "fenglc/pgadmin4"
    ports:
     - "8888:5050"
    volumes:
     - myteststack_mydata2:/var/lib/pgadmin
#volumes:
#  mydata2:
